### ISSUE TITLE
attempt to subtract with overflow

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#1479]
There's a flaky test `histogram_test_min_value_positive_force_merge_segments`, which is very similar to https://github.com/quickwit-oss/tantivy/issues/1440

```
 --- STDERR:                            tantivy aggregation::bucket::histogram::histogram::tests::histogram_test_min_value_positive_force_merge_segments ---
thread 'merge_thread_3' panicked at 'attempt to subtract with overflow', /home/runner/work/tantivy/tantivy/fastfield_codecs/src/linear.rs:131:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: SystemError("Merge operation failed.")
thread 'aggregation::bucket::histogram::histogram::tests::histogram_test_min_value_positive_force_merge_segments' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/test/src/lib.rs:184:5
```

**Comment by PSeitz** [comment]
It's happening in the estimate code

```
thread 'merge_thread_2' panicked at 'attempt to subtract with overflow', /home/pascal/LinuxData/Development/tantivy/overflow_issue/fastfield_codecs/src/linear.rs:131:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
   3: fastfield_codecs::linear::get_calculated_value
             at ./fastfield_codecs/src/linear.rs:131:9
   4: <fastfield_codecs::linear::LinearInterpolFastFieldSerializer as fastfield_codecs::FastFieldCodecSerializer>::estimate::{{closure}}
             at ./fastfield_codecs/src/linear.rs:226:40
```
