### ISSUE TITLE
Query.explain throws a panic

### ISSUE THREAD

**Issue by aliflux-omo** [quickwit-inc/tantivy#2137]
I tried to use query.explain and it threw this error:
```
thread 'main' panicked at 'assertion failed: self.doc() <= target', tantivy-0.20.2\src\postings\segment_postings.rs:173:9
```

My query was:
```
title:sea^20 body:whale^70
```

**Which version of tantivy are you using?**
0.20.2

**To Reproduce**

To reproduce, just use the sample example in the tantivy docs:
https://tantivy-search.github.io/examples/basic_search.html

But use this query:
```
let query = query_parser.parse_query("title:sea^20 body:whale^70")?;
```

Then use this to get the explanation:
```
let explanation = query.explain(&searcher, doc_address)?;
println!("exp {:?}", explanation.to_pretty_json());
```

The searcher returns correct response, but the explanation throws an error.

The explanation works fine if I remove the weights from query. Or if I remove the field prefixes (e.g. `title:`). But using both doesn't work

**Comment by GodTamIt** [comment]
I'm able to reproduce this. Here's the relevant backtrace.

```
thread 'test_me' panicked at 'assertion failed: self.doc() <= target', src/postings/segment_postings.rs:173:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: <tantivy::postings::segment_postings::SegmentPostings as tantivy::docset::DocSet>::seek
             at ./src/postings/segment_postings.rs:173:9
   4: <tantivy::query::term_query::term_scorer::TermScorer as tantivy::docset::DocSet>::seek
             at ./src/query/term_query/term_scorer.rs:106:9
   5: <alloc::boxed::Box<TDocSet> as tantivy::docset::DocSet>::seek
             at ./src/docset.rs:151:9
   6: <tantivy::query::boost_query::BoostWeight as tantivy::query::weight::Weight>::explain
             at ./src/query/boost_query.rs:77:12
   7: <tantivy::query::boolean_query::boolean_weight::BooleanWeight<TScoreCombiner> as tantivy::query::weight::Weight>::explain
             at ./src/query/boolean_query/boolean_weight.rs:199:48
   8: tantivy::query::query::Query::explain
             at ./src/query/query.rs:141:9
```
