### ISSUE TITLE
Range query for optional fast field panics with Index out of bounds in 0.21.1

### ISSUE THREAD

**Issue by williamho** [quickwit-inc/tantivy#2293]
I tried upgrading to tantivy `0.21.1` and found that some range queries on optional fast field columns were panicking with an index out of bounds error. The error doesn't seem to happen on tantivy `0.21.0`.

---

I was able to reproduce the issue in the `range_query_fast_optional_field_minimum` test (in [fast_field_range_query.rs](https://github.com/quickwit-oss/tantivy/blob/53f2fe1fbee83f22c81e28aaec02fb0628b68966/src/query/range_query/fast_field_range_query.rs#L189-L229)) by increasing the doc count from 1000 to 1000000. Specifically this line:

https://github.com/quickwit-oss/tantivy/blob/53f2fe1fbee83f22c81e28aaec02fb0628b68966/src/query/range_query/fast_field_range_query.rs#L203

Command (after updating the count above):

```
RUST_BACKTRACE=1 cargo test range_query_fast_optional_field_minimum
```

Stack trace:

```
thread 'query::range_query::fast_field_range_query::tests::range_query_fast_optional_field_minimum' panicked at columnar/src/column_index/optional_index/mod.rs:194:26:
index out of bounds: the len is 4 but the index is 4
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:190:5
   3: <tantivy_columnar::column_index::optional_index::OptionalIndex as tantivy_columnar::column_index::optional_index::set::Set<u32>>::rank
             at ./columnar/src/column_index/optional_index/mod.rs:194:26
   4: tantivy_columnar::column_index::ColumnIndex::docid_range_to_rowids
             at ./columnar/src/column_index/mod.rs:135:31
   5: tantivy_columnar::column::Column<T>::get_docids_for_value_range
             at ./columnar/src/column/mod.rs:121:27
...
```

**Comment by PSeitz** [comment]
It's not a regression between `0.21.0` and `0.21.1`, but rather one bugfix exposed another bug.

This is a minimal reproducible example, the panic seems to stem from a off by one error (missing metadata block)

```rust
// columnar/src/tests.rs
#[test]
fn test_optional_index_bug() {
    let mut dataframe_writer = ColumnarWriter::default();
    let num_docs = 65536; // succeeds with 65535 or 65537
    dataframe_writer.record_numerical(100, "score", 80i64);
    let mut buffer: Vec<u8> = Vec::new();
    dataframe_writer
        .serialize(num_docs, None, &mut buffer)
        .unwrap();
    let columnar = ColumnarReader::open(buffer).unwrap();

    let cols: Vec<DynamicColumnHandle> = columnar.read_columns("score").unwrap();
    let col = cols[0].open().unwrap();
    col.column_index().docid_range_to_rowids(0..num_docs);
}
```

index out of bounds: the len is 1 but the index is 1 on `let block_meta = self.block_metas[block_id as usize];`
