### ISSUE TITLE
Flaky Test test_cancel_cpu_intensive_tasks

### ISSUE THREAD

**Issue by PSeitz** [quickwit-inc/tantivy#2403]
https://github.com/quickwit-oss/tantivy/actions/runs/9127888173/job/25099130897?pr=2402
```
running 1 test
test core::executor::tests::test_cancel_cpu_intensive_tasks ... FAILED

failures:

failures:
    core::executor::tests::test_cancel_cpu_intensive_tasks

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 857 filtered out; finished in 0.03s


--- STDERR:              tantivy core::executor::tests::test_cancel_cpu_intensive_tasks ---
thread 'core::executor::tests::test_cancel_cpu_intensive_tasks' panicked at src/core/executor.rs:208:9:
assertion failed: counter.load(Ordering::SeqCst) > 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by PSeitz** [comment]
https://github.com/quickwit-oss/tantivy/pull/2407

**Comment by PSeitz** [comment]
Still flaky
```
--- STDOUT:              tantivy core::executor::tests::test_cancel_cpu_intensive_tasks ---

running 1 test

--- STDERR:              tantivy core::executor::tests::test_cancel_cpu_intensive_tasks ---
thread 'search-test0' panicked at src/core/executor.rs:206:42:
called `Result::unwrap()` on an `Err` value: RecvError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
```

https://github.com/quickwit-oss/tantivy/actions/runs/9250798522/job/25445025346

**Comment by adamreichold** [comment]
#2409 fixes this.
